# This file was generated by @liquid-labs/sdlc-projects-workflow-local-node-build.
# Refer to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-local-
# node-build for further details

#####
# build dist/liq-projects.js
#####

SDLC_LIQ_PROJECTS_JS:=$(DIST)/liq-projects.js
SDLC_LIQ_PROJECTS_JS_ENTRY=$(SRC)/index.js
BUILD_TARGETS+=$(SDLC_LIQ_PROJECTS_JS)

$(SDLC_LIQ_PROJECTS_JS): package.json $(SDLC_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(SDLC_LIQ_PROJECTS_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(SDLC_ROLLUP) --config $(SDLC_ROLLUP_CONFIG)

#####
# end dist/liq-projects.js
#####
